language: node_js
node_js:
  - '8'
services:
  - postgresql
before_script:
  - psql -c 'create database vitis_vinifera_test;' -U postgres
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure: CyEHyVPpdAMkZKh9CKBy3Gh0cRdyflVubAkeY6uKxLlck7zl5Hz8H4O7BlJtGeMqlkz3w2Tx/m3AhWsHKzXwohxkuaJnfIvwGcszp8Dy92vOXDCj0knvA7pD5Pp8GTACYkS2xbFLskOXTdmxwE1M1Yps5Qp1Ctaq/kPcvli15zC4eQ8gIwQR7fiL9UwHkl2TKQa/Y5afiaHJf0l+9vnKViQjgV4QJ1ZpMd1gidLc4MLfNh0xyjxGJbICTSmxPoXDRMtL1kHCTkLei6jyWhsPX6sX6AcjziInKOiLgFLTlefeZB0+yhq+mzvmSM+um2J8kCwY5VlTd6ccIIhjuX86g5Vy0OInVL2GJ5YM2kYfj1Z5ySNKP7KhzC/z7Wu/XHNX8gABtzO6FoUWqBCc8sMovLpNuwrdT3dSL945AWdcr+bzJdmeo52v31bWGkYBd20JLEWhVKkiK/iqNphR3yf9gD5DLil1oBhonahbyu1+zYAOK3XgMLPI2EiVTQyNClvAYxgzcHGjTLuXRHpsL0PzFL2INV+2ytnaNUR3ARh1Bbj1dtejl0DfpCqQZ/MeMsuzk1OJX3wmsWQ3cWWvbB2lvL0eB0l8oaQAMgWEMq3+4cxGJ5LPwqxcPNs2JmdhJeABg7+mqHh47st3J43jrgm8vs923zQ+445sAAW2TGB7Flw=
  app: vitis-vinifera
  skip_cleanup: true
